"""add problem, submission, solve

Revision ID: 1c36d9c34623
Revises: f3f0ff4310bf
Create Date: 2026-07-14 19:01:44.402132

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1c36d9c34623"
down_revision: str | None = "f3f0ff4310bf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "problem",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("difficulty", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("chapter_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("chapter_num", sa.Integer(), nullable=False),
        sa.Column("chapter_title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("chapter_desc", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tags_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("llmc_file", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("summary", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("statement_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("requirements_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("examples_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("constraints_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("note", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("starter_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("rtol", sa.Float(), nullable=False),
        sa.Column("atol", sa.Float(), nullable=False),
        sa.Column("time_limit_ms", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_problem_position"), "problem", ["position"], unique=False)
    op.create_index(op.f("ix_problem_slug"), "problem", ["slug"], unique=True)
    op.create_table(
        "submission",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("problem_id", sa.Integer(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("verdict", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("compile_output", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("results_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("total_time_ms", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["problem_id"],
            ["problem.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_submission_problem_id"), "submission", ["problem_id"], unique=False)
    op.create_index(op.f("ix_submission_user_id"), "submission", ["user_id"], unique=False)
    op.create_table(
        "solve",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("problem_id", sa.Integer(), nullable=False),
        sa.Column("submission_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["problem_id"],
            ["problem.id"],
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["submission.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "problem_id"),
    )
    op.create_index(op.f("ix_solve_problem_id"), "solve", ["problem_id"], unique=False)
    op.create_index(op.f("ix_solve_user_id"), "solve", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_solve_user_id"), table_name="solve")
    op.drop_index(op.f("ix_solve_problem_id"), table_name="solve")
    op.drop_table("solve")
    op.drop_index(op.f("ix_submission_user_id"), table_name="submission")
    op.drop_index(op.f("ix_submission_problem_id"), table_name="submission")
    op.drop_table("submission")
    op.drop_index(op.f("ix_problem_slug"), table_name="problem")
    op.drop_index(op.f("ix_problem_position"), table_name="problem")
    op.drop_table("problem")
    # ### end Alembic commands ###
